config/routes.rb
Rails.application.routes.draw do
  get 'users/show'
  devise_for :users
  root to: 'items#index'
  resources :users, only: [:show, :edit, :update]
  resources :types, only: [:index, :show]
  resources :items do
    resources :purchases, only:[:index, :create]
    resources :comments, only: :create
    resources :likes, only: [:destroy, :create]
    collection do
      get 'search'
    end
  end  
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :comments
  has_many :items
  has_many :purchases
  has_many :likes
  has_many :liked_items, through: :likes, source: :item
  has_one_attached :image

  with_options presence: true do
    validates :nickname
    validates :email, uniqueness: true, format: { with: /\A(?=.*@).*\z/ }
    validates :password, confirmation: true, format: { with: /\A(?=.*?[a-z])(?=.*?[\d])[a-z\d]{6,}+\z/ }
    validates :password_confirmation
    validates :first_name
    validates :family_name
    validates :first_name_kana
    validates :family_name_kana
    validates :birth_date
  end

  with_options format: { with: /\A[ぁ-んァ-ン一-龥]+\z/ } do
    validates :first_name
    validates :family_name
  end

  with_options format: { with: /\A[ァ-ヶー－]+\z/ } do
    validates :first_name_kana
    validates :family_name_kana
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
    @user = User.find(params[:id])
    @items = Item.where(user_id: current_user.id)
  end

  def edit
  end

  def update
    if current_user.update(user_params)
      redirect_to show
    else
      render :edit
    end
  end

  private

  def user_params
    params.require(:user).permit(:nickname, :email, :image)
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/edit.html.erb
<div class="AccountPage__form">
    <%= form_for(current_user) do |f| %>
      <div class="FormField">
        <div class="FormField__name">
          <%= f.label :nickname %>
        </div>
        <div class="FormField__name">
          <%= f.text_field :nickname, autofocus: true %>
        </div>
      </div>
      <div class="FormField">
        <div class="FormField__email">
          <%= f.label :email %>
        </div>
        <div class="FormField__email">
          <%= f.email_field :email %>
        </div>
        <br>
      </div>
      <div class="FormField">
        <div class="FormField__image">
          <%= f.label :image %>
        </div>
        <div class="FormField__image">
          <%= f.file_field :image %>
        </div>
        <br>
      </div>
      <%= f.submit "更新する" %>
      <%= link_to  "もどる", user_path(current_user) %>
       <% end %>

app/views/users/show.html.erb
<%= render "shared/header" %>
<div class="AccountPage">
  <div class="AccountPage__title">
    <h1>
    <%= current_user.nickname %>さんのマイページ
    </h1>
  </div>  
 <br>
  <div class="Account__info">
    <h2>
    <%= link_to "情報を更新する", edit_user_path %>
    </h2>
  </div>
  <table class="detail-table1">
      <tbody>
        <tr>
          <th class="detail-item1">画像</th>
          <% if current_user.image != nil %>
          <td class="detail-value1"><%= current_user.image %></td>
          <% end %>
        </tr>
        <tr>
          <th class="detail-item1">ユーザー</th>
          <td class="detail-value1"><%= current_user.nickname  %></td>
        </tr>
        <tr>
          <th class="detail-item1">Eメール</th>
          <td class="detail-value1"><%= current_user.email  %></td>
        </tr>
        <tr>
          <th class="detail-item1">生年月日</th>
          <td class="detail-value1"><%= current_user.birth_date %></td>
        </tr>
      </tbody>
    </table>
    <div class="AccountPage__title">
    <h1>
    出品した商品
    </h1>
  </div><br>
    <ul class='item-lists'>
     <% @items.each do |item|%>
      <li class='list'>
        <%= link_to item_path(item.id) do %>
         <div class='item-img-content'>
          <%= image_tag item.image, class: "item-img" %>
          <% if item.purchase != nil %>
          <div class='sold-out'>
            <span>Sold Out!!</span>
          </div>
          <% end %>
         </div>
         <div class='item-info'>
          <h3 class='item-name'>
            <%= item.name %>
          </h3>
          <div class='item-price'>
          </div>
         </div>
       <% end %>
      </li>
     <% end %>
    </ul>
  <div class="Account__info">
   <%= link_to "TOPへ戻る", root_path%>
   </div>
  </div>
</div>
<%= render "shared/second-footer"%>